# Generated by Django 5.0.4 on 2024-04-30 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=10)),
                ('Age', models.IntegerField()),
                ('Height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Family_history_overweight', models.CharField(max_length=10)),
                ('FAVC', models.CharField(max_length=10)),
                ('FCVC', models.DecimalField(decimal_places=2, max_digits=5)),
                ('NCP', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CAEC', models.CharField(max_length=10)),
                ('Smoke', models.CharField(max_length=10)),
                ('CH2O', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SCC', models.CharField(max_length=10)),
                ('FAF', models.DecimalField(decimal_places=2, max_digits=5)),
                ('TUE', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CALC', models.CharField(max_length=10)),
                ('MTRANS', models.CharField(max_length=50)),
                ('Health_Status', models.CharField(blank=True, max_length=30, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_health', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
